### ISSUE TITLE
visualize

### ISSUE THREAD

**Issue by zhengxiaozx** [SadilKhan/Text2CAD#4]
Interesting job. I would like to ask how to visualize the CAD Sequence or vec.

**Comment by SadilKhan** [comment]
CAD models (`.step`) can be visualized in FreeCAD software, or using pythonocc (Some demos [here](https://github.com/tpaviot/pythonocc-demos/blob/master/examples/core_display_material_shape.py)).

You can also convert it to mesh (`.stl`) and visualize it in Meshlab or even in VS Code with an extension.

**Comment by SadilKhan** [comment]
To generate the CAD model from vec or json, check [this](https://github.com/SadilKhan/Text2CAD/tree/main/CadSeqProc#2-generate-meshbreppoint-cloud-from-jsonvec)
