### ISSUE TITLE
Prompts Not Found

### ISSUE THREAD

**Issue by dxlcf** [SadilKhan/Text2CAD#5]
Hello, I haven't seen the detailed VLM prompt, NLI prompt, and Multi-Level Natural Language Instruction (NLI) Generation Prompt in the code. Could you please provide this information?

**Comment by SadilKhan** [comment]
Hello @dxlcf ,

Unfortunately, we won't be able to release the data annotation pipeline (this includes the prompts). This is the decision of the team. We are still reviewing all possibilities and the situation may change in the coming future.

Thanks.

**Comment by dxlcf** [comment]
> 你好@dxlcf，
> 
> 不幸的是，我们将无法发布数据注释管道（包括提示）。这是团队的决定。我们仍在审查所有可能性，未来情况可能会发生变化。
> 
> 谢谢。

Ok, thank you for your reply
